///////////////////////////////////////////////////////////////////////////
//                                                                       //
//     _                     _              _ _ _     _   _     _        //
//    | |                   | |            | (_) |   | | | |   (_)       //
//  __| | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___    //
// / _` |/ _ \  | |_ \ / _ \| __|  / _ \/ _| | | __| | __| |_ \| / __|   //
//| (_| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \   //
// \__,_|\___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/   //
//                                                                       //
//                                                                       //
//  __ _ _      _ _ _                                                    //
// / _(_) |    | | | |                                                   //
//| |_ _| | ___| | | |                                                   //
//|  _| | |/ _ \ | | |                                                   //
//| | | | |  __/_|_|_|                                                   //
//|_| |_|_|\___(_|_|_)                                                   //
//                                                                       //
///////////////////////////////////////////////////////////////////////////
//
// If you want to add/update/delete an error code, please follow the
// instructions in the README.md of this project
//

#pragma once

///////////////////////////////////////////////////////////////////////////////
//
// Interface Errors - Interface errors occuring while communicating with the controller
//
///////////////////////////////////////////////////////////////////////////////

#define COM_NO_ERROR                                     0L
#define COM_NO_ERROR__0                                  0L
#define COM_ERROR                                        -1L
#define COM_ERROR__MINUS1                                -1L
#define SEND_ERROR                                       -2L
#define SEND_ERROR__MINUS2                               -2L
#define REC_ERROR                                        -3L
#define REC_ERROR__MINUS3                                -3L
#define NOT_CONNECTED_ERROR                              -4L
#define NOT_CONNECTED_ERROR__MINUS4                      -4L
#define COM_BUFFER_OVERFLOW                              -5L
#define COM_BUFFER_OVERFLOW__MINUS5                      -5L
#define CONNECTION_FAILED                                -6L
#define CONNECTION_FAILED__MINUS6                        -6L
#define COM_TIMEOUT                                      -7L
#define COM_TIMEOUT__MINUS7                              -7L
#define COM_MULTILINE_RESPONSE                           -8L
#define COM_MULTILINE_RESPONSE__MINUS8                   -8L
#define COM_INVALID_ID                                   -9L
#define COM_INVALID_ID__MINUS9                           -9L
#define COM_NOTIFY_EVENT_ERROR                           -10L
#define COM_NOTIFY_EVENT_ERROR__MINUS10                  -10L
#define COM_NOT_IMPLEMENTED                              -11L
#define COM_NOT_IMPLEMENTED__MINUS11                     -11L
#define COM_ECHO_ERROR                                   -12L
#define COM_ECHO_ERROR__MINUS12                          -12L
#define COM_GPIB_EDVR                                    -13L
#define COM_GPIB_EDVR__MINUS13                           -13L
#define COM_GPIB_ECIC                                    -14L
#define COM_GPIB_ECIC__MINUS14                           -14L
#define COM_GPIB_ENOL                                    -15L
#define COM_GPIB_ENOL__MINUS15                           -15L
#define COM_GPIB_EADR                                    -16L
#define COM_GPIB_EADR__MINUS16                           -16L
#define COM_GPIB_EARG                                    -17L
#define COM_GPIB_EARG__MINUS17                           -17L
#define COM_GPIB_ESAC                                    -18L
#define COM_GPIB_ESAC__MINUS18                           -18L
#define COM_GPIB_EABO                                    -19L
#define COM_GPIB_EABO__MINUS19                           -19L
#define COM_GPIB_ENEB                                    -20L
#define COM_GPIB_ENEB__MINUS20                           -20L
#define COM_GPIB_EDMA                                    -21L
#define COM_GPIB_EDMA__MINUS21                           -21L
#define COM_GPIB_EOIP                                    -22L
#define COM_GPIB_EOIP__MINUS22                           -22L
#define COM_GPIB_ECAP                                    -23L
#define COM_GPIB_ECAP__MINUS23                           -23L
#define COM_GPIB_EFSO                                    -24L
#define COM_GPIB_EFSO__MINUS24                           -24L
#define COM_GPIB_EBUS                                    -25L
#define COM_GPIB_EBUS__MINUS25                           -25L
#define COM_GPIB_ESTB                                    -26L
#define COM_GPIB_ESTB__MINUS26                           -26L
#define COM_GPIB_ESRQ                                    -27L
#define COM_GPIB_ESRQ__MINUS27                           -27L
#define COM_GPIB_ETAB                                    -28L
#define COM_GPIB_ETAB__MINUS28                           -28L
#define COM_GPIB_ELCK                                    -29L
#define COM_GPIB_ELCK__MINUS29                           -29L
#define COM_RS_INVALID_DATA_BITS                         -30L
#define COM_RS_INVALID_DATA_BITS__MINUS30                -30L
#define COM_ERROR_RS_SETTINGS                            -31L
#define COM_ERROR_RS_SETTINGS__MINUS31                   -31L
#define COM_INTERNAL_RESOURCES_ERROR                     -32L
#define COM_INTERNAL_RESOURCES_ERROR__MINUS32            -32L
#define COM_DLL_FUNC_ERROR                               -33L
#define COM_DLL_FUNC_ERROR__MINUS33                      -33L
#define COM_FTDIUSB_INVALID_HANDLE                       -34L
#define COM_FTDIUSB_INVALID_HANDLE__MINUS34              -34L
#define COM_FTDIUSB_DEVICE_NOT_FOUND                     -35L
#define COM_FTDIUSB_DEVICE_NOT_FOUND__MINUS35            -35L
#define COM_FTDIUSB_DEVICE_NOT_OPENED                    -36L
#define COM_FTDIUSB_DEVICE_NOT_OPENED__MINUS36           -36L
#define COM_FTDIUSB_IO_ERROR                             -37L
#define COM_FTDIUSB_IO_ERROR__MINUS37                    -37L
#define COM_FTDIUSB_INSUFFICIENT_RESOURCES               -38L
#define COM_FTDIUSB_INSUFFICIENT_RESOURCES__MINUS38      -38L
#define COM_FTDIUSB_INVALID_PARAMETER                    -39L
#define COM_FTDIUSB_INVALID_PARAMETER__MINUS39           -39L
#define COM_FTDIUSB_INVALID_BAUD_RATE                    -40L
#define COM_FTDIUSB_INVALID_BAUD_RATE__MINUS40           -40L
#define COM_FTDIUSB_DEVICE_NOT_OPENED_FOR_ERASE          -41L
#define COM_FTDIUSB_DEVICE_NOT_OPENED_FOR_ERASE__MINUS41 -41L
#define COM_FTDIUSB_DEVICE_NOT_OPENED_FOR_WRITE          -42L
#define COM_FTDIUSB_DEVICE_NOT_OPENED_FOR_WRITE__MINUS42 -42L
#define COM_FTDIUSB_FAILED_TO_WRITE_DEVICE               -43L
#define COM_FTDIUSB_FAILED_TO_WRITE_DEVICE__MINUS43      -43L
#define COM_FTDIUSB_EEPROM_READ_FAILED                   -44L
#define COM_FTDIUSB_EEPROM_READ_FAILED__MINUS44          -44L
#define COM_FTDIUSB_EEPROM_WRITE_FAILED                  -45L
#define COM_FTDIUSB_EEPROM_WRITE_FAILED__MINUS45         -45L
#define COM_FTDIUSB_EEPROM_ERASE_FAILED                  -46L
#define COM_FTDIUSB_EEPROM_ERASE_FAILED__MINUS46         -46L
#define COM_FTDIUSB_EEPROM_NOT_PRESENT                   -47L
#define COM_FTDIUSB_EEPROM_NOT_PRESENT__MINUS47          -47L
#define COM_FTDIUSB_EEPROM_NOT_PROGRAMMED                -48L
#define COM_FTDIUSB_EEPROM_NOT_PROGRAMMED__MINUS48       -48L
#define COM_FTDIUSB_INVALID_ARGS                         -49L
#define COM_FTDIUSB_INVALID_ARGS__MINUS49                -49L
#define COM_FTDIUSB_NOT_SUPPORTED                        -50L
#define COM_FTDIUSB_NOT_SUPPORTED__MINUS50               -50L
#define COM_FTDIUSB_OTHER_ERROR                          -51L
#define COM_FTDIUSB_OTHER_ERROR__MINUS51                 -51L
#define COM_PORT_ALREADY_OPEN                            -52L
#define COM_PORT_ALREADY_OPEN__MINUS52                   -52L
#define COM_PORT_CHECKSUM_ERROR                          -53L
#define COM_PORT_CHECKSUM_ERROR__MINUS53                 -53L
#define COM_SOCKET_NOT_READY                             -54L
#define COM_SOCKET_NOT_READY__MINUS54                    -54L
#define COM_SOCKET_PORT_IN_USE                           -55L
#define COM_SOCKET_PORT_IN_USE__MINUS55                  -55L
#define COM_SOCKET_NOT_CONNECTED                         -56L
#define COM_SOCKET_NOT_CONNECTED__MINUS56                -56L
#define COM_SOCKET_TERMINATED                            -57L
#define COM_SOCKET_TERMINATED__MINUS57                   -57L
#define COM_SOCKET_NO_RESPONSE                           -58L
#define COM_SOCKET_NO_RESPONSE__MINUS58                  -58L
#define COM_SOCKET_INTERRUPTED                           -59L
#define COM_SOCKET_INTERRUPTED__MINUS59                  -59L
#define COM_PCI_INVALID_ID                               -60L
#define COM_PCI_INVALID_ID__MINUS60                      -60L
#define COM_PCI_ACCESS_DENIED                            -61L
#define COM_PCI_ACCESS_DENIED__MINUS61                   -61L
#define COM_SOCKET_HOST_NOT_FOUND                        -62L
#define COM_SOCKET_HOST_NOT_FOUND__MINUS62               -62L
#define COM_DEVICE_CONNECTED                             -63L
#define COM_DEVICE_CONNECTED__MINUS63                    -63L

///////////////////////////////////////////////////////////////////////////////
//
// Dll Errors - DLL errors occured in GCS DLL
//
///////////////////////////////////////////////////////////////////////////////

#define PI_UNKNOWN_AXIS_IDENTIFIER                                                         -1001L
#define PI_UNKNOWN_AXIS_IDENTIFIER__MINUS1001                                              -1001L
#define PI_NR_NAV_OUT_OF_RANGE                                                             -1002L
#define PI_NR_NAV_OUT_OF_RANGE__MINUS1002                                                  -1002L
#define PI_INVALID_SGA                                                                     -1003L
#define PI_INVALID_SGA__MINUS1003                                                          -1003L
#define PI_UNEXPECTED_RESPONSE                                                             -1004L
#define PI_UNEXPECTED_RESPONSE__MINUS1004                                                  -1004L
#define PI_NO_MANUAL_PAD                                                                   -1005L
#define PI_NO_MANUAL_PAD__MINUS1005                                                        -1005L
#define PI_INVALID_MANUAL_PAD_KNOB                                                         -1006L
#define PI_INVALID_MANUAL_PAD_KNOB__MINUS1006                                              -1006L
#define PI_INVALID_MANUAL_PAD_AXIS                                                         -1007L
#define PI_INVALID_MANUAL_PAD_AXIS__MINUS1007                                              -1007L
#define PI_CONTROLLER_BUSY                                                                 -1008L
#define PI_CONTROLLER_BUSY__MINUS1008                                                      -1008L
#define PI_THREAD_ERROR                                                                    -1009L
#define PI_THREAD_ERROR__MINUS1009                                                         -1009L
#define PI_IN_MACRO_MODE                                                                   -1010L
#define PI_IN_MACRO_MODE__MINUS1010                                                        -1010L
#define PI_NOT_IN_MACRO_MODE                                                               -1011L
#define PI_NOT_IN_MACRO_MODE__MINUS1011                                                    -1011L
#define PI_MACRO_FILE_ERROR                                                                -1012L
#define PI_MACRO_FILE_ERROR__MINUS1012                                                     -1012L
#define PI_NO_MACRO_OR_EMPTY                                                               -1013L
#define PI_NO_MACRO_OR_EMPTY__MINUS1013                                                    -1013L
#define PI_MACRO_EDITOR_ERROR                                                              -1014L
#define PI_MACRO_EDITOR_ERROR__MINUS1014                                                   -1014L
#define PI_INVALID_ARGUMENT                                                                -1015L
#define PI_INVALID_ARGUMENT__MINUS1015                                                     -1015L
#define PI_AXIS_ALREADY_EXISTS                                                             -1016L
#define PI_AXIS_ALREADY_EXISTS__MINUS1016                                                  -1016L
#define PI_INVALID_AXIS_IDENTIFIER                                                         -1017L
#define PI_INVALID_AXIS_IDENTIFIER__MINUS1017                                              -1017L
#define PI_COM_ARRAY_ERROR                                                                 -1018L
#define PI_COM_ARRAY_ERROR__MINUS1018                                                      -1018L
#define PI_COM_ARRAY_RANGE_ERROR                                                           -1019L
#define PI_COM_ARRAY_RANGE_ERROR__MINUS1019                                                -1019L
#define PI_INVALID_SPA_CMD_ID                                                              -1020L
#define PI_INVALID_SPA_CMD_ID__MINUS1020                                                   -1020L
#define PI_NR_AVG_OUT_OF_RANGE                                                             -1021L
#define PI_NR_AVG_OUT_OF_RANGE__MINUS1021                                                  -1021L
#define PI_WAV_SAMPLES_OUT_OF_RANGE                                                        -1022L
#define PI_WAV_SAMPLES_OUT_OF_RANGE__MINUS1022                                             -1022L
#define PI_WAV_FAILED                                                                      -1023L
#define PI_WAV_FAILED__MINUS1023                                                           -1023L
#define PI_MOTION_ERROR                                                                    -1024L
#define PI_MOTION_ERROR__MINUS1024                                                         -1024L
#define PI_RUNNING_MACRO                                                                   -1025L
#define PI_RUNNING_MACRO__MINUS1025                                                        -1025L
#define PI_PZT_CONFIG_FAILED                                                               -1026L
#define PI_PZT_CONFIG_FAILED__MINUS1026                                                    -1026L
#define PI_PZT_CONFIG_INVALID_PARAMS                                                       -1027L
#define PI_PZT_CONFIG_INVALID_PARAMS__MINUS1027                                            -1027L
#define PI_UNKNOWN_CHANNEL_IDENTIFIER                                                      -1028L
#define PI_UNKNOWN_CHANNEL_IDENTIFIER__MINUS1028                                           -1028L
#define PI_WAVE_PARAM_FILE_ERROR                                                           -1029L
#define PI_WAVE_PARAM_FILE_ERROR__MINUS1029                                                -1029L
#define PI_UNKNOWN_WAVE_SET                                                                -1030L
#define PI_UNKNOWN_WAVE_SET__MINUS1030                                                     -1030L
#define PI_WAVE_EDITOR_FUNC_NOT_LOADED                                                     -1031L
#define PI_WAVE_EDITOR_FUNC_NOT_LOADED__MINUS1031                                          -1031L
#define PI_USER_CANCELLED                                                                  -1032L
#define PI_USER_CANCELLED__MINUS1032                                                       -1032L
#define PI_C844_ERROR                                                                      -1033L
#define PI_C844_ERROR__MINUS1033                                                           -1033L
#define PI_DLL_NOT_LOADED                                                                  -1034L
#define PI_DLL_NOT_LOADED__MINUS1034                                                       -1034L
#define PI_PARAMETER_FILE_PROTECTED                                                        -1035L
#define PI_PARAMETER_FILE_PROTECTED__MINUS1035                                             -1035L
#define PI_NO_PARAMETER_FILE_OPENED                                                        -1036L
#define PI_NO_PARAMETER_FILE_OPENED__MINUS1036                                             -1036L
#define PI_STAGE_DOES_NOT_EXIST                                                            -1037L
#define PI_STAGE_DOES_NOT_EXIST__MINUS1037                                                 -1037L
#define PI_PARAMETER_FILE_ALREADY_OPENED                                                   -1038L
#define PI_PARAMETER_FILE_ALREADY_OPENED__MINUS1038                                        -1038L
#define PI_PARAMETER_FILE_OPEN_ERROR                                                       -1039L
#define PI_PARAMETER_FILE_OPEN_ERROR__MINUS1039                                            -1039L
#define PI_INVALID_CONTROLLER_VERSION                                                      -1040L
#define PI_INVALID_CONTROLLER_VERSION__MINUS1040                                           -1040L
#define PI_PARAM_SET_ERROR                                                                 -1041L
#define PI_PARAM_SET_ERROR__MINUS1041                                                      -1041L
#define PI_NUMBER_OF_POSSIBLE_WAVES_EXCEEDED                                               -1042L
#define PI_NUMBER_OF_POSSIBLE_WAVES_EXCEEDED__MINUS1042                                    -1042L
#define PI_NUMBER_OF_POSSIBLE_GENERATORS_EXCEEDED                                          -1043L
#define PI_NUMBER_OF_POSSIBLE_GENERATORS_EXCEEDED__MINUS1043                               -1043L
#define PI_NO_WAVE_FOR_AXIS_DEFINED                                                        -1044L
#define PI_NO_WAVE_FOR_AXIS_DEFINED__MINUS1044                                             -1044L
#define PI_CANT_STOP_OR_START_WAV                                                          -1045L
#define PI_CANT_STOP_OR_START_WAV__MINUS1045                                               -1045L
#define PI_REFERENCE_ERROR                                                                 -1046L
#define PI_REFERENCE_ERROR__MINUS1046                                                      -1046L
#define PI_REQUIRED_WAVE_NOT_FOUND                                                         -1047L
#define PI_REQUIRED_WAVE_NOT_FOUND__MINUS1047                                              -1047L
#define PI_INVALID_SPP_CMD_ID                                                              -1048L
#define PI_INVALID_SPP_CMD_ID__MINUS1048                                                   -1048L
#define PI_STAGE_NAME_ISNT_UNIQUE                                                          -1049L
#define PI_STAGE_NAME_ISNT_UNIQUE__MINUS1049                                               -1049L
#define PI_FILE_TRANSFER_BEGIN_MISSING                                                     -1050L
#define PI_FILE_TRANSFER_BEGIN_MISSING__MINUS1050                                          -1050L
#define PI_FILE_TRANSFER_ERROR_TEMP_FILE                                                   -1051L
#define PI_FILE_TRANSFER_ERROR_TEMP_FILE__MINUS1051                                        -1051L
#define PI_FILE_TRANSFER_CRC_ERROR                                                         -1052L
#define PI_FILE_TRANSFER_CRC_ERROR__MINUS1052                                              -1052L
#define PI_COULDNT_FIND_PISTAGES_DAT                                                       -1053L
#define PI_COULDNT_FIND_PISTAGES_DAT__MINUS1053                                            -1053L
#define PI_NO_WAVE_RUNNING                                                                 -1054L
#define PI_NO_WAVE_RUNNING__MINUS1054                                                      -1054L
#define PI_INVALID_PASSWORD                                                                -1055L
#define PI_INVALID_PASSWORD__MINUS1055                                                     -1055L
#define PI_OPM_COM_ERROR                                                                   -1056L
#define PI_OPM_COM_ERROR__MINUS1056                                                        -1056L
#define I_WAVE_EDITOR_WRONG_PARAMNUM                                                       -1057L
#define I_WAVE_EDITOR_WRONG_PARAMNUM__MINUS1057                                            -1057L
#define I_WAVE_EDITOR_FREQUENCY_OUT_OF_RANGE                                               -1058L
#define I_WAVE_EDITOR_FREQUENCY_OUT_OF_RANGE__MINUS1058                                    -1058L
#define I_WAVE_EDITOR_WRONG_IP_VALUE                                                       -1059L
#define I_WAVE_EDITOR_WRONG_IP_VALUE__MINUS1059                                            -1059L
#define I_WAVE_EDITOR_WRONG_DP_VALUE                                                       -1060L
#define I_WAVE_EDITOR_WRONG_DP_VALUE__MINUS1060                                            -1060L
#define I_WAVE_EDITOR_WRONG_ITEM_VALUE                                                     -1061L
#define I_WAVE_EDITOR_WRONG_ITEM_VALUE__MINUS1061                                          -1061L
#define I_WAVE_EDITOR_MISSING_GRAPH_COMPONENT                                              -1062L
#define I_WAVE_EDITOR_MISSING_GRAPH_COMPONENT__MINUS1062                                   -1062L
#define PI_EXT_PROFILE_UNALLOWED_CMD                                                       -1063L
#define PI_EXT_PROFILE_UNALLOWED_CMD__MINUS1063                                            -1063L
#define PI_EXT_PROFILE_EXPECTING_MOTION_ERROR                                              -1064L
#define PI_EXT_PROFILE_EXPECTING_MOTION_ERROR__MINUS1064                                   -1064L
#define PI_EXT_PROFILE_ACTIVE                                                              -1065L
#define PI_EXT_PROFILE_ACTIVE__MINUS1065                                                   -1065L
#define PI_EXT_PROFILE_INDEX_OUT_OF_RANGE                                                  -1066L
#define PI_EXT_PROFILE_INDEX_OUT_OF_RANGE__MINUS1066                                       -1066L
#define PI_PROFILE_GENERATOR_NO_PROFILE                                                    -1067L
#define PI_PROFILE_GENERATOR_NO_PROFILE__MINUS1067                                         -1067L
#define PI_PROFILE_GENERATOR_OUT_OF_LIMITS                                                 -1068L
#define PI_PROFILE_GENERATOR_OUT_OF_LIMITS__MINUS1068                                      -1068L
#define PI_PROFILE_GENERATOR_UNKNOWN_PARAMETER                                             -1069L
#define PI_PROFILE_GENERATOR_UNKNOWN_PARAMETER__MINUS1069                                  -1069L
#define PI_PROFILE_GENERATOR_PAR_OUT_OF_RANGE                                              -1070L
#define PI_PROFILE_GENERATOR_PAR_OUT_OF_RANGE__MINUS1070                                   -1070L
#define PI_EXT_PROFILE_OUT_OF_MEMORY                                                       -1071L
#define PI_EXT_PROFILE_OUT_OF_MEMORY__MINUS1071                                            -1071L
#define PI_EXT_PROFILE_WRONG_CLUSTER                                                       -1072L
#define PI_EXT_PROFILE_WRONG_CLUSTER__MINUS1072                                            -1072L
#define PI_EXT_PROFILE_UNKNOWN_CLUSTER_IDENTIFIER                                          -1073L
#define PI_EXT_PROFILE_UNKNOWN_CLUSTER_IDENTIFIER__MINUS1073                               -1073L
#define PI_INVALID_DEVICE_DRIVER_VERSION                                                   -1074L
#define PI_INVALID_DEVICE_DRIVER_VERSION__MINUS1074                                        -1074L
#define PI_INVALID_LIBRARY_VERSION                                                         -1075L
#define PI_INVALID_LIBRARY_VERSION__MINUS1075                                              -1075L
#define PI_INTERFACE_LOCKED                                                                -1076L
#define PI_INTERFACE_LOCKED__MINUS1076                                                     -1076L
#define PI_PARAM_DAT_FILE_INVALID_VERSION                                                  -1077L
#define PI_PARAM_DAT_FILE_INVALID_VERSION__MINUS1077                                       -1077L
#define PI_CANNOT_WRITE_TO_PARAM_DAT_FILE                                                  -1078L
#define PI_CANNOT_WRITE_TO_PARAM_DAT_FILE__MINUS1078                                       -1078L
#define PI_CANNOT_CREATE_PARAM_DAT_FILE                                                    -1079L
#define PI_CANNOT_CREATE_PARAM_DAT_FILE__MINUS1079                                         -1079L
#define PI_PARAM_DAT_FILE_INVALID_REVISION                                                 -1080L
#define PI_PARAM_DAT_FILE_INVALID_REVISION__MINUS1080                                      -1080L
#define PI_USERSTAGES_DAT_FILE_INVALID_REVISION                                            -1081L
#define PI_USERSTAGES_DAT_FILE_INVALID_REVISION__MINUS1081                                 -1081L
#define PI_SOFTWARE_TIMEOUT                                                                -1082L
#define PI_SOFTWARE_TIMEOUT__MINUS1082                                                     -1082L
#define PI_WRONG_DATA_TYPE                                                                 -1083L
#define PI_WRONG_DATA_TYPE__MINUS1083                                                      -1083L
#define PI_DIFFERENT_ARRAY_SIZES                                                           -1084L
#define PI_DIFFERENT_ARRAY_SIZES__MINUS1084                                                -1084L
#define PI_PARAM_NOT_FOUND_IN_PARAM_DAT_FILE                                               -1085L
#define PI_PARAM_NOT_FOUND_IN_PARAM_DAT_FILE__MINUS1085                                    -1085L
#define PI_MACRO_RECORDING_NOT_ALLOWED_IN_THIS_MODE                                        -1086L
#define PI_MACRO_RECORDING_NOT_ALLOWED_IN_THIS_MODE__MINUS1086                             -1086L
#define PI_USER_CANCELLED_COMMAND                                                          -1087L
#define PI_USER_CANCELLED_COMMAND__MINUS1087                                               -1087L
#define PI_TOO_FEW_GCS_DATA                                                                -1088L
#define PI_TOO_FEW_GCS_DATA__MINUS1088                                                     -1088L
#define PI_TOO_MANY_GCS_DATA                                                               -1089L
#define PI_TOO_MANY_GCS_DATA__MINUS1089                                                    -1089L
#define PI_GCS_DATA_READ_ERROR                                                             -1090L
#define PI_GCS_DATA_READ_ERROR__MINUS1090                                                  -1090L
#define PI_WRONG_NUMBER_OF_INPUT_ARGUMENTS                                                 -1091L
#define PI_WRONG_NUMBER_OF_INPUT_ARGUMENTS__MINUS1091                                      -1091L
#define PI_FAILED_TO_CHANGE_CCL_LEVEL                                                      -1092L
#define PI_FAILED_TO_CHANGE_CCL_LEVEL__MINUS1092                                           -1092L
#define PI_FAILED_TO_SWITCH_OFF_SERVO                                                      -1093L
#define PI_FAILED_TO_SWITCH_OFF_SERVO__MINUS1093                                           -1093L
#define PI_FAILED_TO_SET_SINGLE_PARAMETER_WHILE_PERFORMING_CST                             -1094L
#define PI_FAILED_TO_SET_SINGLE_PARAMETER_WHILE_PERFORMING_CST__MINUS1094                  -1094L
#define PI_ERROR_CONTROLLER_REBOOT                                                         -1095L
#define PI_ERROR_CONTROLLER_REBOOT__MINUS1095                                              -1095L
#define PI_ERROR_AT_QHPA                                                                   -1096L
#define PI_ERROR_AT_QHPA__MINUS1096                                                        -1096L
#define PI_QHPA_NONCOMPLIANT_WITH_GCS                                                      -1097L
#define PI_QHPA_NONCOMPLIANT_WITH_GCS__MINUS1097                                           -1097L
#define PI_FAILED_TO_READ_QSPA                                                             -1098L
#define PI_FAILED_TO_READ_QSPA__MINUS1098                                                  -1098L
#define PI_PAM_FILE_WRONG_VERSION                                                          -1099L
#define PI_PAM_FILE_WRONG_VERSION__MINUS1099                                               -1099L
#define PI_PAM_FILE_INVALID_FORMAT                                                         -1100L
#define PI_PAM_FILE_INVALID_FORMAT__MINUS1100                                              -1100L
#define PI_INCOMPLETE_INFORMATION                                                          -1101L
#define PI_INCOMPLETE_INFORMATION__MINUS1101                                               -1101L
#define PI_NO_VALUE_AVAILABLE                                                              -1102L
#define PI_NO_VALUE_AVAILABLE__MINUS1102                                                   -1102L
#define PI_NO_PAM_FILE_OPEN                                                                -1103L
#define PI_NO_PAM_FILE_OPEN__MINUS1103                                                     -1103L
#define PI_INVALID_VALUE                                                                   -1104L
#define PI_INVALID_VALUE__MINUS1104                                                        -1104L
#define PI_UNKNOWN_PARAMETER                                                               -1105L
#define PI_UNKNOWN_PARAMETER__MINUS1105                                                    -1105L
#define PI_RESPONSE_TO_QSEP_FAILED                                                         -1106L
#define PI_RESPONSE_TO_QSEP_FAILED__MINUS1106                                              -1106L
#define PI_RESPONSE_TO_QSPA_FAILED                                                         -1107L
#define PI_RESPONSE_TO_QSPA_FAILED__MINUS1107                                              -1107L
#define PI_ERROR_IN_CST_VALIDATION                                                         -1108L
#define PI_ERROR_IN_CST_VALIDATION__MINUS1108                                              -1108L
#define PI_ERROR_PAM_FILE_HAS_DUPLICATE_ENTRY_WITH_DIFFERENT_VALUES                        -1109L
#define PI_ERROR_PAM_FILE_HAS_DUPLICATE_ENTRY_WITH_DIFFERENT_VALUES__MINUS1109             -1109L
#define PI_ERROR_FILE_NO_SIGNATURE                                                         -1110L
#define PI_ERROR_FILE_NO_SIGNATURE__MINUS1110                                              -1110L
#define PI_ERROR_FILE_INVALID_SIGNATURE                                                    -1111L
#define PI_ERROR_FILE_INVALID_SIGNATURE__MINUS1111                                         -1111L
#define PI_ERROR_CANNOT_DETERMINE_ACTUAL_END_OF_TRAVEL_WHILE_PLATFORM_IS_MOVING            -1112L
#define PI_ERROR_CANNOT_DETERMINE_ACTUAL_END_OF_TRAVEL_WHILE_PLATFORM_IS_MOVING__MINUS1112 -1112L
#define PI_ERROR_AT_QIDN                                                                   -1113L
#define PI_ERROR_AT_QIDN__MINUS1113                                                        -1113L
#define PI_ERROR_AT_MAC_DEF                                                                -1114L
#define PI_ERROR_AT_MAC_DEF__MINUS1114                                                     -1114L
#define PI_CONTROLLER_OR_CONTROLLER_VERSION_DOES_NOT_EXIST_IN_PISTAGES_DATABASE            -1115L
#define PI_CONTROLLER_OR_CONTROLLER_VERSION_DOES_NOT_EXIST_IN_PISTAGES_DATABASE__MINUS1115 -1115L
#define PI_NOT_ENOUGH_MEMORY                                                               -1116L
#define PI_NOT_ENOUGH_MEMORY__MINUS1116                                                    -1116L
#define PI_ERROR_AXIS_RUNTIME_ERROR                                                        -1117L
#define PI_ERROR_AXIS_RUNTIME_ERROR__MINUS1117                                             -1117L
#define PI_ERROR_SYSTEM_RUNTIME_CRITICAL_ERROR                                             -1118L
#define PI_ERROR_SYSTEM_RUNTIME_CRITICAL_ERROR__MINUS1118                                  -1118L
#define PI_PARAMETER_DB_INVALID_STAGE_TYPE_FORMAT                                          -10000L
#define PI_PARAMETER_DB_INVALID_STAGE_TYPE_FORMAT__MINUS10000                              -10000L
#define PI_PARAMETER_DB_SYSTEM_NOT_AVAILABLE                                               -10001L
#define PI_PARAMETER_DB_SYSTEM_NOT_AVAILABLE__MINUS10001                                   -10001L
#define PI_PARAMETER_DB_FAILED_TO_ESTABLISH_CONNECTION                                     -10002L
#define PI_PARAMETER_DB_FAILED_TO_ESTABLISH_CONNECTION__MINUS10002                         -10002L
#define PI_PARAMETER_DB_COMMUNICATION_ERROR                                                -10003L
#define PI_PARAMETER_DB_COMMUNICATION_ERROR__MINUS10003                                    -10003L
#define PI_PARAMETER_DB_ERROR_WHILE_QUERYING_PARAMETERS                                    -10004L
#define PI_PARAMETER_DB_ERROR_WHILE_QUERYING_PARAMETERS__MINUS10004                        -10004L
#define PI_PARAMETER_DB_SYSTEM_ALREADY_EXISTS                                              -10005L
#define PI_PARAMETER_DB_SYSTEM_ALREADY_EXISTS__MINUS10005                                  -10005L
#define PI_PARAMETER_DB_QHPA_CONTANS_UNKNOWN_PAM_IDS                                       -10006L
#define PI_PARAMETER_DB_QHPA_CONTANS_UNKNOWN_PAM_IDS__MINUS10006                           -10006L
#define PI_PARAMETER_DB_AND_QHPA_ARE_INCONSISTENT                                          -10007L
#define PI_PARAMETER_DB_AND_QHPA_ARE_INCONSISTENT__MINUS10007                              -10007L
#define PI_PARAMETER_DB_SYSTEM_COULD_NOT_BE_ADDED                                          -10008L
#define PI_PARAMETER_DB_SYSTEM_COULD_NOT_BE_ADDED__MINUS10008                              -10008L
#define PI_PARAMETER_DB_SYSTEM_COULD_NOT_BE_REMOVED                                        -10009L
#define PI_PARAMETER_DB_SYSTEM_COULD_NOT_BE_REMOVED__MINUS10009                            -10009L
#define PI_PARAMETER_DB_CONTROLLER_DB_PARAMETERS_MISMATCH                                  -10010L
#define PI_PARAMETER_DB_CONTROLLER_DB_PARAMETERS_MISMATCH__MINUS10010                      -10010L
#define PI_PARAMETER_DB_DATABASE_IS_OUTDATED                                               -10011L
#define PI_PARAMETER_DB_DATABASE_IS_OUTDATED__MINUS10011                                   -10011L
#define PI_PARAMETER_DB_AND_HPA_MISMATCH_STRICT                                            -10012L
#define PI_PARAMETER_DB_AND_HPA_MISMATCH_STRICT__MINUS10012                                -10012L
#define PI_PARAMETER_DB_AND_HPA_MISMATCH_LOOSE                                             -10013L
#define PI_PARAMETER_DB_AND_HPA_MISMATCH_LOOSE__MINUS10013                                 -10013L
#define PI_PARAMETER_DB_FAILED_TO_SET_PARAMETERS_CORRECTLY                                 -10014L
#define PI_PARAMETER_DB_FAILED_TO_SET_PARAMETERS_CORRECTLY__MINUS10014                     -10014L
#define PI_PARAMETER_DB_MISSING_PARAMETER_DEFINITIONS_IN_DATABASE                          -10015L
#define PI_PARAMETER_DB_MISSING_PARAMETER_DEFINITIONS_IN_DATABASE__MINUS10015              -10015L
#define PI_PARAMETER_DB_MISSING_FIRMWARE_FEATURE_ON_CONTROLLER                             -10016L
#define PI_PARAMETER_DB_MISSING_FIRMWARE_FEATURE_ON_CONTROLLER__MINUS10016                 -10016L

///////////////////////////////////////////////////////////////////////////////
//
// Controller Errors - Errors set by the controller or the GCS DLL
//
///////////////////////////////////////////////////////////////////////////////

#define PI_CNTR_NO_ERROR                                      0L
#define PI_CNTR_NO_ERROR__0                                   0L
#define PI_CNTR_PARAM_SYNTAX                                  1L
#define PI_CNTR_PARAM_SYNTAX__1                               1L
#define PI_CNTR_UNKNOWN_COMMAND                               2L
#define PI_CNTR_UNKNOWN_COMMAND__2                            2L
#define PI_CNTR_COMMAND_TOO_LONG                              3L
#define PI_CNTR_COMMAND_TOO_LONG__3                           3L
#define PI_CNTR_SCAN_ERROR                                    4L
#define PI_CNTR_SCAN_ERROR__4                                 4L
#define PI_CNTR_MOVE_WITHOUT_REF_OR_NO_SERVO                  5L
#define PI_CNTR_MOVE_WITHOUT_REF_OR_NO_SERVO__5               5L
#define PI_CNTR_INVALID_SGA_PARAM                             6L
#define PI_CNTR_INVALID_SGA_PARAM__6                          6L
#define PI_CNTR_POS_OUT_OF_LIMITS                             7L
#define PI_CNTR_POS_OUT_OF_LIMITS__7                          7L
#define PI_CNTR_VEL_OUT_OF_LIMITS                             8L
#define PI_CNTR_VEL_OUT_OF_LIMITS__8                          8L
#define PI_CNTR_SET_PIVOT_NOT_POSSIBLE                        9L
#define PI_CNTR_SET_PIVOT_NOT_POSSIBLE__9                     9L
#define PI_CNTR_STOP                                          10L
#define PI_CNTR_STOP__10                                      10L
#define PI_CNTR_SST_OR_SCAN_RANGE                             11L
#define PI_CNTR_SST_OR_SCAN_RANGE__11                         11L
#define PI_CNTR_INVALID_SCAN_AXES                             12L
#define PI_CNTR_INVALID_SCAN_AXES__12                         12L
#define PI_CNTR_INVALID_NAV_PARAM                             13L
#define PI_CNTR_INVALID_NAV_PARAM__13                         13L
#define PI_CNTR_INVALID_ANALOG_INPUT                          14L
#define PI_CNTR_INVALID_ANALOG_INPUT__14                      14L
#define PI_CNTR_INVALID_AXIS_IDENTIFIER                       15L
#define PI_CNTR_INVALID_AXIS_IDENTIFIER__15                   15L
#define PI_CNTR_INVALID_STAGE_NAME                            16L
#define PI_CNTR_INVALID_STAGE_NAME__16                        16L
#define PI_CNTR_PARAM_OUT_OF_RANGE                            17L
#define PI_CNTR_PARAM_OUT_OF_RANGE__17                        17L
#define PI_CNTR_INVALID_MACRO_NAME                            18L
#define PI_CNTR_INVALID_MACRO_NAME__18                        18L
#define PI_CNTR_MACRO_RECORD                                  19L
#define PI_CNTR_MACRO_RECORD__19                              19L
#define PI_CNTR_MACRO_NOT_FOUND                               20L
#define PI_CNTR_MACRO_NOT_FOUND__20                           20L
#define PI_CNTR_AXIS_HAS_NO_BRAKE                             21L
#define PI_CNTR_AXIS_HAS_NO_BRAKE__21                         21L
#define PI_CNTR_DOUBLE_AXIS                                   22L
#define PI_CNTR_DOUBLE_AXIS__22                               22L
#define PI_CNTR_ILLEGAL_AXIS                                  23L
#define PI_CNTR_ILLEGAL_AXIS__23                              23L
#define PI_CNTR_PARAM_NR                                      24L
#define PI_CNTR_PARAM_NR__24                                  24L
#define PI_CNTR_INVALID_REAL_NR                               25L
#define PI_CNTR_INVALID_REAL_NR__25                           25L
#define PI_CNTR_MISSING_PARAM                                 26L
#define PI_CNTR_MISSING_PARAM__26                             26L
#define PI_CNTR_SOFT_LIMIT_OUT_OF_RANGE                       27L
#define PI_CNTR_SOFT_LIMIT_OUT_OF_RANGE__27                   27L
#define PI_CNTR_NO_MANUAL_PAD                                 28L
#define PI_CNTR_NO_MANUAL_PAD__28                             28L
#define PI_CNTR_NO_JUMP                                       29L
#define PI_CNTR_NO_JUMP__29                                   29L
#define PI_CNTR_INVALID_JUMP                                  30L
#define PI_CNTR_INVALID_JUMP__30                              30L
#define PI_CNTR_AXIS_HAS_NO_REFERENCE                         31L
#define PI_CNTR_AXIS_HAS_NO_REFERENCE__31                     31L
#define PI_CNTR_STAGE_HAS_NO_LIM_SWITCH                       32L
#define PI_CNTR_STAGE_HAS_NO_LIM_SWITCH__32                   32L
#define PI_CNTR_NO_RELAY_CARD                                 33L
#define PI_CNTR_NO_RELAY_CARD__33                             33L
#define PI_CNTR_CMD_NOT_ALLOWED_FOR_STAGE                     34L
#define PI_CNTR_CMD_NOT_ALLOWED_FOR_STAGE__34                 34L
#define PI_CNTR_NO_DIGITAL_INPUT                              35L
#define PI_CNTR_NO_DIGITAL_INPUT__35                          35L
#define PI_CNTR_NO_DIGITAL_OUTPUT                             36L
#define PI_CNTR_NO_DIGITAL_OUTPUT__36                         36L
#define PI_CNTR_NO_MCM                                        37L
#define PI_CNTR_NO_MCM__37                                    37L
#define PI_CNTR_INVALID_MCM                                   38L
#define PI_CNTR_INVALID_MCM__38                               38L
#define PI_CNTR_INVALID_CNTR_NUMBER                           39L
#define PI_CNTR_INVALID_CNTR_NUMBER__39                       39L
#define PI_CNTR_NO_JOYSTICK_CONNECTED                         40L
#define PI_CNTR_NO_JOYSTICK_CONNECTED__40                     40L
#define PI_CNTR_INVALID_EGE_AXIS                              41L
#define PI_CNTR_INVALID_EGE_AXIS__41                          41L
#define PI_CNTR_SLAVE_POSITION_OUT_OF_RANGE                   42L
#define PI_CNTR_SLAVE_POSITION_OUT_OF_RANGE__42               42L
#define PI_CNTR_COMMAND_EGE_SLAVE                             43L
#define PI_CNTR_COMMAND_EGE_SLAVE__43                         43L
#define PI_CNTR_JOYSTICK_CALIBRATION_FAILED                   44L
#define PI_CNTR_JOYSTICK_CALIBRATION_FAILED__44               44L
#define PI_CNTR_REFERENCING_FAILED                            45L
#define PI_CNTR_REFERENCING_FAILED__45                        45L
#define PI_CNTR_OPM_MISSING                                   46L
#define PI_CNTR_OPM_MISSING__46                               46L
#define PI_CNTR_OPM_NOT_INITIALIZED                           47L
#define PI_CNTR_OPM_NOT_INITIALIZED__47                       47L
#define PI_CNTR_OPM_COM_ERROR                                 48L
#define PI_CNTR_OPM_COM_ERROR__48                             48L
#define PI_CNTR_MOVE_TO_LIMIT_SWITCH_FAILED                   49L
#define PI_CNTR_MOVE_TO_LIMIT_SWITCH_FAILED__49               49L
#define PI_CNTR_REF_WITH_REF_DISABLED                         50L
#define PI_CNTR_REF_WITH_REF_DISABLED__50                     50L
#define PI_CNTR_AXIS_UNDER_JOYSTICK_CONTROL                   51L
#define PI_CNTR_AXIS_UNDER_JOYSTICK_CONTROL__51               51L
#define PI_CNTR_COMMUNICATION_ERROR                           52L
#define PI_CNTR_COMMUNICATION_ERROR__52                       52L
#define PI_CNTR_DYNAMIC_MOVE_IN_PROCESS                       53L
#define PI_CNTR_DYNAMIC_MOVE_IN_PROCESS__53                   53L
#define PI_CNTR_UNKNOWN_PARAMETER                             54L
#define PI_CNTR_UNKNOWN_PARAMETER__54                         54L
#define PI_CNTR_NO_REP_RECORDED                               55L
#define PI_CNTR_NO_REP_RECORDED__55                           55L
#define PI_CNTR_INVALID_PASSWORD                              56L
#define PI_CNTR_INVALID_PASSWORD__56                          56L
#define PI_CNTR_INVALID_RECORDER_CHAN                         57L
#define PI_CNTR_INVALID_RECORDER_CHAN__57                     57L
#define PI_CNTR_INVALID_RECORDER_SRC_OPT                      58L
#define PI_CNTR_INVALID_RECORDER_SRC_OPT__58                  58L
#define PI_CNTR_INVALID_RECORDER_SRC_CHAN                     59L
#define PI_CNTR_INVALID_RECORDER_SRC_CHAN__59                 59L
#define PI_CNTR_PARAM_PROTECTION                              60L
#define PI_CNTR_PARAM_PROTECTION__60                          60L
#define PI_CNTR_AUTOZERO_RUNNING                              61L
#define PI_CNTR_AUTOZERO_RUNNING__61                          61L
#define PI_CNTR_NO_LINEAR_AXIS                                62L
#define PI_CNTR_NO_LINEAR_AXIS__62                            62L
#define PI_CNTR_INIT_RUNNING                                  63L
#define PI_CNTR_INIT_RUNNING__63                              63L
#define PI_CNTR_READ_ONLY_PARAMETER                           64L
#define PI_CNTR_READ_ONLY_PARAMETER__64                       64L
#define PI_CNTR_PAM_NOT_FOUND                                 65L
#define PI_CNTR_PAM_NOT_FOUND__65                             65L
#define PI_CNTR_VOL_OUT_OF_LIMITS                             66L
#define PI_CNTR_VOL_OUT_OF_LIMITS__66                         66L
#define PI_CNTR_WAVE_TOO_LARGE                                67L
#define PI_CNTR_WAVE_TOO_LARGE__67                            67L
#define PI_CNTR_NOT_ENOUGH_DDL_MEMORY                         68L
#define PI_CNTR_NOT_ENOUGH_DDL_MEMORY__68                     68L
#define PI_CNTR_DDL_TIME_DELAY_TOO_LARGE                      69L
#define PI_CNTR_DDL_TIME_DELAY_TOO_LARGE__69                  69L
#define PI_CNTR_DIFFERENT_ARRAY_LENGTH                        70L
#define PI_CNTR_DIFFERENT_ARRAY_LENGTH__70                    70L
#define PI_CNTR_GEN_SINGLE_MODE_RESTART                       71L
#define PI_CNTR_GEN_SINGLE_MODE_RESTART__71                   71L
#define PI_CNTR_ANALOG_TARGET_ACTIVE                          72L
#define PI_CNTR_ANALOG_TARGET_ACTIVE__72                      72L
#define PI_CNTR_WAVE_GENERATOR_ACTIVE                         73L
#define PI_CNTR_WAVE_GENERATOR_ACTIVE__73                     73L
#define PI_CNTR_AUTOZERO_DISABLED                             74L
#define PI_CNTR_AUTOZERO_DISABLED__74                         74L
#define PI_CNTR_NO_WAVE_SELECTED                              75L
#define PI_CNTR_NO_WAVE_SELECTED__75                          75L
#define PI_CNTR_IF_BUFFER_OVERRUN                             76L
#define PI_CNTR_IF_BUFFER_OVERRUN__76                         76L
#define PI_CNTR_NOT_ENOUGH_RECORDED_DATA                      77L
#define PI_CNTR_NOT_ENOUGH_RECORDED_DATA__77                  77L
#define PI_CNTR_TABLE_DEACTIVATED                             78L
#define PI_CNTR_TABLE_DEACTIVATED__78                         78L
#define PI_CNTR_OPENLOOP_VALUE_SET_WHEN_SERVO_ON              79L
#define PI_CNTR_OPENLOOP_VALUE_SET_WHEN_SERVO_ON__79          79L
#define PI_CNTR_RAM_ERROR                                     80L
#define PI_CNTR_RAM_ERROR__80                                 80L
#define PI_CNTR_MACRO_UNKNOWN_COMMAND                         81L
#define PI_CNTR_MACRO_UNKNOWN_COMMAND__81                     81L
#define PI_CNTR_MACRO_PC_ERROR                                82L
#define PI_CNTR_MACRO_PC_ERROR__82                            82L
#define PI_CNTR_JOYSTICK_ACTIVE                               83L
#define PI_CNTR_JOYSTICK_ACTIVE__83                           83L
#define PI_CNTR_MOTOR_IS_OFF                                  84L
#define PI_CNTR_MOTOR_IS_OFF__84                              84L
#define PI_CNTR_ONLY_IN_MACRO                                 85L
#define PI_CNTR_ONLY_IN_MACRO__85                             85L
#define PI_CNTR_JOYSTICK_UNKNOWN_AXIS                         86L
#define PI_CNTR_JOYSTICK_UNKNOWN_AXIS__86                     86L
#define PI_CNTR_JOYSTICK_UNKNOWN_ID                           87L
#define PI_CNTR_JOYSTICK_UNKNOWN_ID__87                       87L
#define PI_CNTR_REF_MODE_IS_ON                                88L
#define PI_CNTR_REF_MODE_IS_ON__88                            88L
#define PI_CNTR_NOT_ALLOWED_IN_CURRENT_MOTION_MODE            89L
#define PI_CNTR_NOT_ALLOWED_IN_CURRENT_MOTION_MODE__89        89L
#define PI_CNTR_DIO_AND_TRACING_NOT_POSSIBLE                  90L
#define PI_CNTR_DIO_AND_TRACING_NOT_POSSIBLE__90              90L
#define PI_CNTR_COLLISION                                     91L
#define PI_CNTR_COLLISION__91                                 91L
#define PI_CNTR_SLAVE_NOT_FAST_ENOUGH                         92L
#define PI_CNTR_SLAVE_NOT_FAST_ENOUGH__92                     92L
#define PI_CNTR_CMD_NOT_ALLOWED_WHILE_AXIS_IN_MOTION          93L
#define PI_CNTR_CMD_NOT_ALLOWED_WHILE_AXIS_IN_MOTION__93      93L
#define PI_CNTR_OPEN_LOOP_JOYSTICK_ENABLED                    94L
#define PI_CNTR_OPEN_LOOP_JOYSTICK_ENABLED__94                94L
#define PI_CNTR_INVALID_SERVO_STATE_FOR_PARAMETER             95L
#define PI_CNTR_INVALID_SERVO_STATE_FOR_PARAMETER__95         95L
#define PI_CNTR_UNKNOWN_STAGE_NAME                            96L
#define PI_CNTR_UNKNOWN_STAGE_NAME__96                        96L
#define PI_CNTR_INVALID_VALUE_LENGTH                          97L
#define PI_CNTR_INVALID_VALUE_LENGTH__97                      97L
#define PI_CNTR_AUTOZERO_FAILED                               98L
#define PI_CNTR_AUTOZERO_FAILED__98                           98L
#define PI_CNTR_SENSOR_VOLTAGE_OFF                            99L
#define PI_CNTR_SENSOR_VOLTAGE_OFF__99                        99L
#define PI_LABVIEW_ERROR                                      100L
#define PI_LABVIEW_ERROR__100                                 100L
#define PI_CNTR_NO_AXIS                                       200L
#define PI_CNTR_NO_AXIS__200                                  200L
#define PI_CNTR_NO_AXIS_PARAM_FILE                            201L
#define PI_CNTR_NO_AXIS_PARAM_FILE__201                       201L
#define PI_CNTR_INVALID_AXIS_PARAM_FILE                       202L
#define PI_CNTR_INVALID_AXIS_PARAM_FILE__202                  202L
#define PI_CNTR_NO_AXIS_PARAM_BACKUP                          203L
#define PI_CNTR_NO_AXIS_PARAM_BACKUP__203                     203L
#define PI_CNTR_RESERVED_204                                  204L
#define PI_CNTR_RESERVED_204__204                             204L
#define PI_CNTR_SMO_WITH_SERVO_ON                             205L
#define PI_CNTR_SMO_WITH_SERVO_ON__205                        205L
#define PI_CNTR_UUDECODE_INCOMPLETE_HEADER                    206L
#define PI_CNTR_UUDECODE_INCOMPLETE_HEADER__206               206L
#define PI_CNTR_UUDECODE_NOTHING_TO_DECODE                    207L
#define PI_CNTR_UUDECODE_NOTHING_TO_DECODE__207               207L
#define PI_CNTR_UUDECODE_ILLEGAL_FORMAT                       208L
#define PI_CNTR_UUDECODE_ILLEGAL_FORMAT__208                  208L
#define PI_CNTR_CRC32_ERROR                                   209L
#define PI_CNTR_CRC32_ERROR__209                              209L
#define PI_CNTR_ILLEGAL_FILENAME                              210L
#define PI_CNTR_ILLEGAL_FILENAME__210                         210L
#define PI_CNTR_FILE_NOT_FOUND                                211L
#define PI_CNTR_FILE_NOT_FOUND__211                           211L
#define PI_CNTR_FILE_WRITE_ERROR                              212L
#define PI_CNTR_FILE_WRITE_ERROR__212                         212L
#define PI_CNTR_DTR_HINDERS_VELOCITY_CHANGE                   213L
#define PI_CNTR_DTR_HINDERS_VELOCITY_CHANGE__213              213L
#define PI_CNTR_POSITION_UNKNOWN                              214L
#define PI_CNTR_POSITION_UNKNOWN__214                         214L
#define PI_CNTR_CONN_POSSIBLY_BROKEN                          215L
#define PI_CNTR_CONN_POSSIBLY_BROKEN__215                     215L
#define PI_CNTR_ON_LIMIT_SWITCH                               216L
#define PI_CNTR_ON_LIMIT_SWITCH__216                          216L
#define PI_CNTR_UNEXPECTED_STRUT_STOP                         217L
#define PI_CNTR_UNEXPECTED_STRUT_STOP__217                    217L
#define PI_CNTR_POSITION_BASED_ON_ESTIMATION                  218L
#define PI_CNTR_POSITION_BASED_ON_ESTIMATION__218             218L
#define PI_CNTR_POSITION_BASED_ON_INTERPOLATION               219L
#define PI_CNTR_POSITION_BASED_ON_INTERPOLATION__219          219L
#define PI_CNTR_INTERPOLATION_FIFO_UNDERRUN                   220L
#define PI_CNTR_INTERPOLATION_FIFO_UNDERRUN__220              220L
#define PI_CNTR_INTERPOLATION_FIFO_OVERFLOW                   221L
#define PI_CNTR_INTERPOLATION_FIFO_OVERFLOW__221              221L
#define PI_CNTR_INVALID_HANDLE                                230L
#define PI_CNTR_INVALID_HANDLE__230                           230L
#define PI_CNTR_NO_BIOS_FOUND                                 231L
#define PI_CNTR_NO_BIOS_FOUND__231                            231L
#define PI_CNTR_SAVE_SYS_CFG_FAILED                           232L
#define PI_CNTR_SAVE_SYS_CFG_FAILED__232                      232L
#define PI_CNTR_LOAD_SYS_CFG_FAILED                           233L
#define PI_CNTR_LOAD_SYS_CFG_FAILED__233                      233L
#define PI_CNTR_SEND_BUFFER_OVERFLOW                          301L
#define PI_CNTR_SEND_BUFFER_OVERFLOW__301                     301L
#define PI_CNTR_VOLTAGE_OUT_OF_LIMITS                         302L
#define PI_CNTR_VOLTAGE_OUT_OF_LIMITS__302                    302L
#define PI_CNTR_OPEN_LOOP_MOTION_SET_WHEN_SERVO_ON            303L
#define PI_CNTR_OPEN_LOOP_MOTION_SET_WHEN_SERVO_ON__303       303L
#define PI_CNTR_RECEIVING_BUFFER_OVERFLOW                     304L
#define PI_CNTR_RECEIVING_BUFFER_OVERFLOW__304                304L
#define PI_CNTR_EEPROM_ERROR                                  305L
#define PI_CNTR_EEPROM_ERROR__305                             305L
#define PI_CNTR_I2C_ERROR                                     306L
#define PI_CNTR_I2C_ERROR__306                                306L
#define PI_CNTR_RECEIVING_TIMEOUT                             307L
#define PI_CNTR_RECEIVING_TIMEOUT__307                        307L
#define PI_CNTR_TIMEOUT                                       308L
#define PI_CNTR_TIMEOUT__308                                  308L
#define PI_CNTR_MACRO_OUT_OF_SPACE                            309L
#define PI_CNTR_MACRO_OUT_OF_SPACE__309                       309L
#define PI_CNTR_EUI_OLDVERSION_CFGDATA                        310L
#define PI_CNTR_EUI_OLDVERSION_CFGDATA__310                   310L
#define PI_CNTR_EUI_INVALID_CFGDATA                           311L
#define PI_CNTR_EUI_INVALID_CFGDATA__311                      311L
#define PI_CNTR_HARDWARE_ERROR                                333L
#define PI_CNTR_HARDWARE_ERROR__333                           333L
#define PI_CNTR_WAV_INDEX_ERROR                               400L
#define PI_CNTR_WAV_INDEX_ERROR__400                          400L
#define PI_CNTR_WAV_NOT_DEFINED                               401L
#define PI_CNTR_WAV_NOT_DEFINED__401                          401L
#define PI_CNTR_WAV_TYPE_NOT_SUPPORTED                        402L
#define PI_CNTR_WAV_TYPE_NOT_SUPPORTED__402                   402L
#define PI_CNTR_WAV_LENGTH_EXCEEDS_LIMIT                      403L
#define PI_CNTR_WAV_LENGTH_EXCEEDS_LIMIT__403                 403L
#define PI_CNTR_WAV_PARAMETER_NR                              404L
#define PI_CNTR_WAV_PARAMETER_NR__404                         404L
#define PI_CNTR_WAV_PARAMETER_OUT_OF_LIMIT                    405L
#define PI_CNTR_WAV_PARAMETER_OUT_OF_LIMIT__405               405L
#define PI_CNTR_WGO_BIT_NOT_SUPPORTED                         406L
#define PI_CNTR_WGO_BIT_NOT_SUPPORTED__406                    406L
#define PI_CNTR_EMERGENCY_STOP_BUTTON_ACTIVATED               500L
#define PI_CNTR_EMERGENCY_STOP_BUTTON_ACTIVATED__500          500L
#define PI_CNTR_EMERGENCY_STOP_BUTTON_WAS_ACTIVATED           501L
#define PI_CNTR_EMERGENCY_STOP_BUTTON_WAS_ACTIVATED__501      501L
#define PI_CNTR_REDUNDANCY_LIMIT_EXCEEDED                     502L
#define PI_CNTR_REDUNDANCY_LIMIT_EXCEEDED__502                502L
#define PI_CNTR_COLLISION_SWITCH_ACTIVATED                    503L
#define PI_CNTR_COLLISION_SWITCH_ACTIVATED__503               503L
#define PI_CNTR_FOLLOWING_ERROR                               504L
#define PI_CNTR_FOLLOWING_ERROR__504                          504L
#define PI_CNTR_SENSOR_SIGNAL_INVALID                         505L
#define PI_CNTR_SENSOR_SIGNAL_INVALID__505                    505L
#define PI_CNTR_SERVO_LOOP_UNSTABLE                           506L
#define PI_CNTR_SERVO_LOOP_UNSTABLE__506                      506L
#define PI_CNTR_LOST_SPI_SLAVE_CONNECTION                     507L
#define PI_CNTR_LOST_SPI_SLAVE_CONNECTION__507                507L
#define PI_CNTR_MOVE_ATTEMPT_NOT_PERMITTED                    508L
#define PI_CNTR_MOVE_ATTEMPT_NOT_PERMITTED__508               508L
#define PI_CNTR_TRIGGER_EMERGENCY_STOP                        509L
#define PI_CNTR_TRIGGER_EMERGENCY_STOP__509                   509L
#define PI_CNTR_CS_DOES_NOT_EXIST                             530L
#define PI_CNTR_CS_DOES_NOT_EXIST__530                        530L
#define PI_CNTR_PARENT_CS_DOES_NOT_EXIST                      531L
#define PI_CNTR_PARENT_CS_DOES_NOT_EXIST__531                 531L
#define PI_CNTR_CS_IN_USE                                     532L
#define PI_CNTR_CS_IN_USE__532                                532L
#define PI_CNTR_CS_DEFINITION_IS_CYCLIC                       533L
#define PI_CNTR_CS_DEFINITION_IS_CYCLIC__533                  533L
#define PI_CNTR_HEXAPOD_IN_MOTION                             536L
#define PI_CNTR_HEXAPOD_IN_MOTION__536                        536L
#define PI_CNTR_CS_TYPE_CANNOT_BE_ENABLED                     537L
#define PI_CNTR_CS_TYPE_CANNOT_BE_ENABLED__537                537L
#define PI_CNTR_CS_PARENT_IDENTICAL_TO_CHILD                  539L
#define PI_CNTR_CS_PARENT_IDENTICAL_TO_CHILD__539             539L
#define PI_CNTR_CS_DEFINITION_INCONSISTENT                    540L
#define PI_CNTR_CS_DEFINITION_INCONSISTENT__540               540L
#define PI_CNTR_CS_NOT_IN_SAME_CHAIN                          542L
#define PI_CNTR_CS_NOT_IN_SAME_CHAIN__542                     542L
#define PI_CNTR_CS_MEMORY_FULL                                543L
#define PI_CNTR_CS_MEMORY_FULL__543                           543L
#define PI_CNTR_SPI_COMMAND_NOT_SUPPORTED                     544L
#define PI_CNTR_SPI_COMMAND_NOT_SUPPORTED__544                544L
#define PI_CNTR_SOFTLIMITS_INVALID                            545L
#define PI_CNTR_SOFTLIMITS_INVALID__545                       545L
#define PI_CNTR_CS_WRITE_PROTECTED                            546L
#define PI_CNTR_CS_WRITE_PROTECTED__546                       546L
#define PI_CNTR_CS_CONTENT_FROM_CONFIG_FILE                   547L
#define PI_CNTR_CS_CONTENT_FROM_CONFIG_FILE__547              547L
#define PI_CNTR_CS_CANNOT_BE_LINKED                           548L
#define PI_CNTR_CS_CANNOT_BE_LINKED__548                      548L
#define PI_CNTR_KSB_CS_ROTATION_ONLY                          549L
#define PI_CNTR_KSB_CS_ROTATION_ONLY__549                     549L
#define PI_CNTR_CS_DATA_CANNOT_BE_QUERIED                     551L
#define PI_CNTR_CS_DATA_CANNOT_BE_QUERIED__551                551L
#define PI_CNTR_CS_COMBINATION_DOES_NOT_EXIST                 552L
#define PI_CNTR_CS_COMBINATION_DOES_NOT_EXIST__552            552L
#define PI_CNTR_CS_COMBINATION_INVALID                        553L
#define PI_CNTR_CS_COMBINATION_INVALID__553                   553L
#define PI_CNTR_CS_TYPE_DOES_NOT_EXIST                        554L
#define PI_CNTR_CS_TYPE_DOES_NOT_EXIST__554                   554L
#define PI_CNTR_UNKNOWN_ERROR                                 555L
#define PI_CNTR_UNKNOWN_ERROR__555                            555L
#define PI_CNTR_CS_TYPE_NOT_ENABLED                           556L
#define PI_CNTR_CS_TYPE_NOT_ENABLED__556                      556L
#define PI_CNTR_CS_NAME_INVALID                               557L
#define PI_CNTR_CS_NAME_INVALID__557                          557L
#define PI_CNTR_CS_GENERAL_FILE_MISSING                       558L
#define PI_CNTR_CS_GENERAL_FILE_MISSING__558                  558L
#define PI_CNTR_CS_LEVELING_FILE_MISSING                      559L
#define PI_CNTR_CS_LEVELING_FILE_MISSING__559                 559L
#define PI_CNTR_NOT_ENOUGH_MEMORY                             601L
#define PI_CNTR_NOT_ENOUGH_MEMORY__601                        601L
#define PI_CNTR_HW_VOLTAGE_ERROR                              602L
#define PI_CNTR_HW_VOLTAGE_ERROR__602                         602L
#define PI_CNTR_HW_TEMPERATURE_ERROR                          603L
#define PI_CNTR_HW_TEMPERATURE_ERROR__603                     603L
#define PI_CNTR_POSITION_ERROR_TOO_HIGH                       604L
#define PI_CNTR_POSITION_ERROR_TOO_HIGH__604                  604L
#define PI_CNTR_INPUT_OUT_OF_RANGE                            606L
#define PI_CNTR_INPUT_OUT_OF_RANGE__606                       606L
#define PI_CNTR_NO_INTEGER                                    607L
#define PI_CNTR_NO_INTEGER__607                               607L
#define PI_CNTR_FAST_ALIGNMENT_PROCESS_IS_NOT_RUNNING         608L
#define PI_CNTR_FAST_ALIGNMENT_PROCESS_IS_NOT_RUNNING__608    608L
#define PI_CNTR_FAST_ALIGNMENT_PROCESS_IS_NOT_PAUSED          609L
#define PI_CNTR_FAST_ALIGNMENT_PROCESS_IS_NOT_PAUSED__609     609L
#define PI_CNTR_UNABLE_TO_SET_PARAM_WITH_SPA                  650L
#define PI_CNTR_UNABLE_TO_SET_PARAM_WITH_SPA__650             650L
#define PI_CNTR_PHASE_FINDING_ERROR                           651L
#define PI_CNTR_PHASE_FINDING_ERROR__651                      651L
#define PI_CNTR_SENSOR_SETUP_ERROR                            652L
#define PI_CNTR_SENSOR_SETUP_ERROR__652                       652L
#define PI_CNTR_SENSOR_COMM_ERROR                             653L
#define PI_CNTR_SENSOR_COMM_ERROR__653                        653L
#define PI_CNTR_MOTOR_AMPLIFIER_ERROR                         654L
#define PI_CNTR_MOTOR_AMPLIFIER_ERROR__654                    654L
#define PI_CNTR_OVER_CURR_PROTEC_TRIGGERED_BY_I2T             655L
#define PI_CNTR_OVER_CURR_PROTEC_TRIGGERED_BY_I2T__655        655L
#define PI_CNTR_OVER_CURR_PROTEC_TRIGGERED_BY_AMP_MODULE      656L
#define PI_CNTR_OVER_CURR_PROTEC_TRIGGERED_BY_AMP_MODULE__656 656L
#define PI_CNTR_SAFETY_STOP_TRIGGERED                         657L
#define PI_CNTR_SAFETY_STOP_TRIGGERED__657                    657L
#define PI_SENSOR_OFF                                         658L
#define PI_SENSOR_OFF__658                                    658L
#define PI_CNTR_PARAM_CONFLICT                                659L
#define PI_CNTR_PARAM_CONFLICT__659                           659L
#define PI_CNTR_COMMAND_NOT_ALLOWED_IN_EXTERNAL_MODE          700L
#define PI_CNTR_COMMAND_NOT_ALLOWED_IN_EXTERNAL_MODE__700     700L
#define PI_CNTR_EXTERNAL_MODE_ERROR                           710L
#define PI_CNTR_EXTERNAL_MODE_ERROR__710                      710L
#define PI_CNTR_INVALID_MODE_OF_OPERATION                     715L
#define PI_CNTR_INVALID_MODE_OF_OPERATION__715                715L
#define PI_CNTR_FIRMWARE_STOPPED_BY_CMD                       716L
#define PI_CNTR_FIRMWARE_STOPPED_BY_CMD__716                  716L
#define PI_CNTR_EXTERNAL_MODE_DRIVER_MISSING                  717L
#define PI_CNTR_EXTERNAL_MODE_DRIVER_MISSING__717             717L
#define PI_CNTR_CONFIGURATION_FAILURE_EXTERNAL_MODE           718L
#define PI_CNTR_CONFIGURATION_FAILURE_EXTERNAL_MODE__718      718L
#define PI_CNTR_EXTERNAL_MODE_CYCLETIME_INVALID               719L
#define PI_CNTR_EXTERNAL_MODE_CYCLETIME_INVALID__719          719L
#define PI_CNTR_BRAKE_ACTIVATED                               720L
#define PI_CNTR_BRAKE_ACTIVATED__720                          720L
#define PI_CNTR_DRIVE_STATE_TRANSITION_ERROR                  725L
#define PI_CNTR_DRIVE_STATE_TRANSITION_ERROR__725             725L
#define PI_CNTR_SURFACEDETECTION_RUNNING                      731L
#define PI_CNTR_SURFACEDETECTION_RUNNING__731                 731L
#define PI_CNTR_SURFACEDETECTION_FAILED                       732L
#define PI_CNTR_SURFACEDETECTION_FAILED__732                  732L
#define PI_CNTR_FIELDBUS_IS_ACTIVE                            733L
#define PI_CNTR_FIELDBUS_IS_ACTIVE__733                       733L
#define PI_CNTR_TOO_MANY_NESTED_MACROS                        1000L
#define PI_CNTR_TOO_MANY_NESTED_MACROS__1000                  1000L
#define PI_CNTR_MACRO_ALREADY_DEFINED                         1001L
#define PI_CNTR_MACRO_ALREADY_DEFINED__1001                   1001L
#define PI_CNTR_NO_MACRO_RECORDING                            1002L
#define PI_CNTR_NO_MACRO_RECORDING__1002                      1002L
#define PI_CNTR_INVALID_MAC_PARAM                             1003L
#define PI_CNTR_INVALID_MAC_PARAM__1003                       1003L
#define PI_CNTR_MACRO_DELETE_ERROR                            1004L
#define PI_CNTR_MACRO_DELETE_ERROR__1004                      1004L
#define PI_CNTR_CONTROLLER_BUSY                               1005L
#define PI_CNTR_CONTROLLER_BUSY__1005                         1005L
#define PI_CNTR_INVALID_IDENTIFIER                            1006L
#define PI_CNTR_INVALID_IDENTIFIER__1006                      1006L
#define PI_CNTR_UNKNOWN_VARIABLE_OR_ARGUMENT                  1007L
#define PI_CNTR_UNKNOWN_VARIABLE_OR_ARGUMENT__1007            1007L
#define PI_CNTR_RUNNING_MACRO                                 1008L
#define PI_CNTR_RUNNING_MACRO__1008                           1008L
#define PI_CNTR_MACRO_INVALID_OPERATOR                        1009L
#define PI_CNTR_MACRO_INVALID_OPERATOR__1009                  1009L
#define PI_CNTR_MACRO_NO_ANSWER                               1010L
#define PI_CNTR_MACRO_NO_ANSWER__1010                         1010L
#define PI_CMD_NOT_VALID_IN_MACRO_MODE                        1011L
#define PI_CMD_NOT_VALID_IN_MACRO_MODE__1011                  1011L
#define PI_CNTR_ERROR_IN_MACRO                                1012L
#define PI_CNTR_ERROR_IN_MACRO__1012                          1012L
#define PI_CNTR_NO_MACRO_OR_EMPTY                             1013L
#define PI_CNTR_NO_MACRO_OR_EMPTY__1013                       1013L
#define PI_CNTR_INVALID_ARGUMENT                              1015L
#define PI_CNTR_INVALID_ARGUMENT__1015                        1015L
#define PI_CNTR_MOTION_ERROR                                  1024L
#define PI_CNTR_MOTION_ERROR__1024                            1024L
#define PI_CNTR_MAX_MOTOR_OUTPUT_REACHED                      1025L
#define PI_CNTR_MAX_MOTOR_OUTPUT_REACHED__1025                1025L
#define PI_CNTR_UNKNOWN_CHANNEL_IDENTIFIER                    1028L
#define PI_CNTR_UNKNOWN_CHANNEL_IDENTIFIER__1028              1028L
#define PI_CNTR_EXT_PROFILE_UNALLOWED_CMD                     1063L
#define PI_CNTR_EXT_PROFILE_UNALLOWED_CMD__1063               1063L
#define PI_CNTR_EXT_PROFILE_EXPECTING_MOTION_ERROR            1064L
#define PI_CNTR_EXT_PROFILE_EXPECTING_MOTION_ERROR__1064      1064L
#define PI_CNTR_PROFILE_ACTIVE                                1065L
#define PI_CNTR_PROFILE_ACTIVE__1065                          1065L
#define PI_CNTR_PROFILE_INDEX_OUT_OF_RANGE                    1066L
#define PI_CNTR_PROFILE_INDEX_OUT_OF_RANGE__1066              1066L
#define PI_CNTR_PROFILE_OUT_OF_MEMORY                         1071L
#define PI_CNTR_PROFILE_OUT_OF_MEMORY__1071                   1071L
#define PI_CNTR_PROFILE_WRONG_CLUSTER                         1072L
#define PI_CNTR_PROFILE_WRONG_CLUSTER__1072                   1072L
#define PI_CNTR_PROFILE_UNKNOWN_CLUSTER_IDENTIFIER            1073L
#define PI_CNTR_PROFILE_UNKNOWN_CLUSTER_IDENTIFIER__1073      1073L
#define PI_CNTR_TOO_MANY_TCP_CONNECTIONS_OPEN                 1090L
#define PI_CNTR_TOO_MANY_TCP_CONNECTIONS_OPEN__1090           1090L
#define PI_CNTR_ALREADY_HAS_SERIAL_NUMBER                     2000L
#define PI_CNTR_ALREADY_HAS_SERIAL_NUMBER__2000               2000L
#define PI_CNTR_FEATURE_LICENSE_INVALID                       2100L
#define PI_CNTR_FEATURE_LICENSE_INVALID__2100                 2100L
#define PI_CNTR_SECTOR_ERASE_FAILED                           4000L
#define PI_CNTR_SECTOR_ERASE_FAILED__4000                     4000L
#define PI_CNTR_FLASH_PROGRAM_FAILED                          4001L
#define PI_CNTR_FLASH_PROGRAM_FAILED__4001                    4001L
#define PI_CNTR_FLASH_READ_FAILED                             4002L
#define PI_CNTR_FLASH_READ_FAILED__4002                       4002L
#define PI_CNTR_HW_MATCHCODE_ERROR                            4003L
#define PI_CNTR_HW_MATCHCODE_ERROR__4003                      4003L
#define PI_CNTR_FW_MATCHCODE_ERROR                            4004L
#define PI_CNTR_FW_MATCHCODE_ERROR__4004                      4004L
#define PI_CNTR_HW_VERSION_ERROR                              4005L
#define PI_CNTR_HW_VERSION_ERROR__4005                        4005L
#define PI_CNTR_FW_VERSION_ERROR                              4006L
#define PI_CNTR_FW_VERSION_ERROR__4006                        4006L
#define PI_CNTR_FW_UPDATE_ERROR                               4007L
#define PI_CNTR_FW_UPDATE_ERROR__4007                         4007L
#define PI_CNTR_FW_CRC_PAR_ERROR                              4008L
#define PI_CNTR_FW_CRC_PAR_ERROR__4008                        4008L
#define PI_CNTR_FW_CRC_FW_ERROR                               4009L
#define PI_CNTR_FW_CRC_FW_ERROR__4009                         4009L
#define PI_CNTR_INVALID_PCC_SCAN_DATA                         5000L
#define PI_CNTR_INVALID_PCC_SCAN_DATA__5000                   5000L
#define PI_CNTR_PCC_SCAN_RUNNING                              5001L
#define PI_CNTR_PCC_SCAN_RUNNING__5001                        5001L
#define PI_CNTR_INVALID_PCC_AXIS                              5002L
#define PI_CNTR_INVALID_PCC_AXIS__5002                        5002L
#define PI_CNTR_PCC_SCAN_OUT_OF_RANGE                         5003L
#define PI_CNTR_PCC_SCAN_OUT_OF_RANGE__5003                   5003L
#define PI_CNTR_PCC_TYPE_NOT_EXISTING                         5004L
#define PI_CNTR_PCC_TYPE_NOT_EXISTING__5004                   5004L
#define PI_CNTR_PCC_PAM_ERROR                                 5005L
#define PI_CNTR_PCC_PAM_ERROR__5005                           5005L
#define PI_CNTR_PCC_TABLE_ARRAY_TOO_LARGE                     5006L
#define PI_CNTR_PCC_TABLE_ARRAY_TOO_LARGE__5006               5006L
#define PI_CNTR_NEXLINE_ERROR                                 5100L
#define PI_CNTR_NEXLINE_ERROR__5100                           5100L
#define PI_CNTR_CHANNEL_ALREADY_USED                          5101L
#define PI_CNTR_CHANNEL_ALREADY_USED__5101                    5101L
#define PI_CNTR_NEXLINE_TABLE_TOO_SMALL                       5102L
#define PI_CNTR_NEXLINE_TABLE_TOO_SMALL__5102                 5102L
#define PI_CNTR_RNP_WITH_SERVO_ON                             5103L
#define PI_CNTR_RNP_WITH_SERVO_ON__5103                       5103L
#define PI_CNTR_RNP_NEEDED                                    5104L
#define PI_CNTR_RNP_NEEDED__5104                              5104L
#define PI_CNTR_AXIS_NOT_CONFIGURED                           5200L
#define PI_CNTR_AXIS_NOT_CONFIGURED__5200                     5200L
#define PI_CNTR_FREQU_ANALYSIS_FAILED                         5300L
#define PI_CNTR_FREQU_ANALYSIS_FAILED__5300                   5300L
#define PI_CNTR_FREQU_ANALYSIS_RUNNING                        5301L
#define PI_CNTR_FREQU_ANALYSIS_RUNNING__5301                  5301L
#define PI_CNTR_SENSOR_ABS_INVALID_VALUE                      6000L
#define PI_CNTR_SENSOR_ABS_INVALID_VALUE__6000                6000L
#define PI_CNTR_SENSOR_ABS_WRITE_ERROR                        6001L
#define PI_CNTR_SENSOR_ABS_WRITE_ERROR__6001                  6001L
#define PI_CNTR_SENSOR_ABS_READ_ERROR                         6002L
#define PI_CNTR_SENSOR_ABS_READ_ERROR__6002                   6002L
#define PI_CNTR_SENSOR_ABS_CRC_ERROR                          6003L
#define PI_CNTR_SENSOR_ABS_CRC_ERROR__6003                    6003L
#define PI_CNTR_SENSOR_ABS_ERROR                              6004L
#define PI_CNTR_SENSOR_ABS_ERROR__6004                        6004L
#define PI_CNTR_SENSOR_ABS_OVERFLOW                           6005L
#define PI_CNTR_SENSOR_ABS_OVERFLOW__6005                     6005L

///////////////////////////////////////////////////////////////////////////////
//
// UMF Errors
//
///////////////////////////////////////////////////////////////////////////////

#define PI_ERROR_NO_ERROR                                                0L
#define PI_ERROR_NO_ERROR__0                                             0L
#define PI_ERROR_CMD_NUMBER_OF_ARGUMENTS                                 8961L
#define PI_ERROR_CMD_NUMBER_OF_ARGUMENTS__8961                           8961L
#define PI_ERROR_CMD_UNKNOWN_COMMAND                                     8962L
#define PI_ERROR_CMD_UNKNOWN_COMMAND__8962                               8962L
#define PI_ERROR_CMD_COMMAND_LEVEL_TOO_LOW_FOR_COMMAND_ACCESS            8965L
#define PI_ERROR_CMD_COMMAND_LEVEL_TOO_LOW_FOR_COMMAND_ACCESS__8965      8965L
#define PI_ERROR_CMD_INVALID_PWD                                         8970L
#define PI_ERROR_CMD_INVALID_PWD__8970                                   8970L
#define PI_ERROR_PARAM_WRONG_DATA_TYPE                                   16385L
#define PI_ERROR_PARAM_WRONG_DATA_TYPE__16385                            16385L
#define PI_ERROR_PARAM_UNKNOWN_PARAMETER_ID                              17154L
#define PI_ERROR_PARAM_UNKNOWN_PARAMETER_ID__17154                       17154L
#define PI_ERROR_PARAM_COMMAND_LEVEL_TOO_LOW_FOR_PARAMETER_ACCESS        17157L
#define PI_ERROR_PARAM_COMMAND_LEVEL_TOO_LOW_FOR_PARAMETER_ACCESS__17157 17157L
#define PI_ERROR_PARAM_INVALID_VALUE                                     17162L
#define PI_ERROR_PARAM_INVALID_VALUE__17162                              17162L
#define PI_ERROR_PARAM_WRONG_PARAMETER_TYPE                              17163L
#define PI_ERROR_PARAM_WRONG_PARAMETER_TYPE__17163                       17163L
#define PI_ERROR_PARAM_VALUE_OUT_OF_RANGE                                17192L
#define PI_ERROR_PARAM_VALUE_OUT_OF_RANGE__17192                         17192L
#define PI_ERROR_MOTION_ON_LIMIT_SWITCH                                  21255L
#define PI_ERROR_MOTION_ON_LIMIT_SWITCH__21255                           21255L
#define PI_ERROR_MOTION_INVALID_MODE_OF_OPERATION                        21258L
#define PI_ERROR_MOTION_INVALID_MODE_OF_OPERATION__21258                 21258L
#define PI_ERROR_MOTION_MOVE_WITHOUT_REF                                 21259L
#define PI_ERROR_MOTION_MOVE_WITHOUT_REF__21259                          21259L
#define PI_ERROR_MOTION_TARGET_OUT_OF_RANGE                              21288L
#define PI_ERROR_MOTION_TARGET_OUT_OF_RANGE__21288                       21288L
#define PI_ERROR_MOTION_AXIS_DISABLED                                    21308L
#define PI_ERROR_MOTION_AXIS_DISABLED__21308                             21308L
#define PI_ERROR_MOTION_LIMIT_SWITCH_ACTIVATED                           21767L
#define PI_ERROR_MOTION_LIMIT_SWITCH_ACTIVATED__21767                    21767L
#define PI_ERROR_MOTION_OVER_CURRENT_PROTECTION                          21800L
#define PI_ERROR_MOTION_OVER_CURRENT_PROTECTION__21800                   21800L
#define PI_ERROR_MOTION_POSITION_ERROR_TOO_LARGE                         21801L
#define PI_ERROR_MOTION_POSITION_ERROR_TOO_LARGE__21801                  21801L
#define PI_ERROR_RECORDER_MAX_DATA_RECORDER_NUMBER_REACHED               24583L
#define PI_ERROR_RECORDER_MAX_DATA_RECORDER_NUMBER_REACHED__24583        24583L
#define PI_ERROR_RECORDER_ALREADY_REGISTERED                             24596L
#define PI_ERROR_RECORDER_ALREADY_REGISTERED__24596                      24596L
#define PI_ERROR_RECORDER_NOT_IN_CONFIG_MODE                             25354L
#define PI_ERROR_RECORDER_NOT_IN_CONFIG_MODE__25354                      25354L
#define PI_ERROR_RECORDER_ALREADY_RUNNING                                25355L
#define PI_ERROR_RECORDER_ALREADY_RUNNING__25355                         25355L
#define PI_ERROR_RECORDER_TRACE_DOES_NOT_EXIST                           25384L
#define PI_ERROR_RECORDER_TRACE_DOES_NOT_EXIST__25384                    25384L
#define PI_ERROR_RECORDER_NOT_ENOUGH_RECORDED_DATA                       25414L
#define PI_ERROR_RECORDER_NOT_ENOUGH_RECORDED_DATA__25414                25414L
#define PI_ERROR_RECORDER_TRACES_NOT_CONFIGURED                          25415L
#define PI_ERROR_RECORDER_TRACES_NOT_CONFIGURED__25415                   25415L
#define PI_ERROR_COM_COMMUNICATION_ERROR                                 33380L
#define PI_ERROR_COM_COMMUNICATION_ERROR__33380                          33380L
#define PI_ERROR_COM_FW_INDEX_UNKNOWN                                    33538L
#define PI_ERROR_COM_FW_INDEX_UNKNOWN__33538                             33538L
#define PI_ERROR_COM_TIMEOUT                                             33796L
#define PI_ERROR_COM_TIMEOUT__33796                                      33796L
#define PI_ERROR_COM_INVALID_SOCKET                                      33803L
#define PI_ERROR_COM_INVALID_SOCKET__33803                               33803L
#define PI_ERROR_SYS_UNIT_NOT_INITIALIZED                                36867L
#define PI_ERROR_SYS_UNIT_NOT_INITIALIZED__36867                         36867L
#define PI_ERROR_SYS_MAX_CONNECTION_NUMBER_REACHED                       36871L
#define PI_ERROR_SYS_MAX_CONNECTION_NUMBER_REACHED__36871                36871L
#define PI_ERROR_SYS_CONNECTION_OUTPUT_WRONG_ARGUMENTS                   36874L
#define PI_ERROR_SYS_CONNECTION_OUTPUT_WRONG_ARGUMENTS__36874            36874L
#define PI_ERROR_SYS_CONNECTION_INPUT_WRONG_ARGUMENTS                    36875L
#define PI_ERROR_SYS_CONNECTION_INPUT_WRONG_ARGUMENTS__36875             36875L
#define PI_ERROR_SYS_WRONG_UNIT_ID_FORMAT                                36876L
#define PI_ERROR_SYS_WRONG_UNIT_ID_FORMAT__36876                         36876L
#define PI_ERROR_SYS_WRONG_DEVICE_ID                                     36877L
#define PI_ERROR_SYS_WRONG_DEVICE_ID__36877                              36877L
#define PI_ERROR_SYS_WRONG_FUNCTION_ID                                   36878L
#define PI_ERROR_SYS_WRONG_FUNCTION_ID__36878                            36878L
#define PI_ERROR_SYS_WRONG_PROXY_ID                                      36879L
#define PI_ERROR_SYS_WRONG_PROXY_ID__36879                               36879L
#define PI_ERROR_SYS_CONNECTION_OUTPUT_INDEX_OUT_OF_RANGE                36904L
#define PI_ERROR_SYS_CONNECTION_OUTPUT_INDEX_OUT_OF_RANGE__36904         36904L
#define PI_ERROR_SYS_INTERFACE_REGISTRATION_FAILED                       36914L
#define PI_ERROR_SYS_INTERFACE_REGISTRATION_FAILED__36914                36914L
#define PI_ERROR_SYS_DEVICE_REGISTRATION_FAILED                          36915L
#define PI_ERROR_SYS_DEVICE_REGISTRATION_FAILED__36915                   36915L
#define PI_ERROR_SYS_PROXY_REGISTRATION_FAILED                           36916L
#define PI_ERROR_SYS_PROXY_REGISTRATION_FAILED__36916                    36916L
#define PI_ERROR_SYS_INPUT_PORT_ALREADY_CONNECTED                        37140L
#define PI_ERROR_SYS_INPUT_PORT_ALREADY_CONNECTED__37140                 37140L
#define PI_ERROR_SYS_UNIT_ALREADY_REGISTERED                             37141L
#define PI_ERROR_SYS_UNIT_ALREADY_REGISTERED__37141                      37141L
#define PI_ERROR_SYS_CONNECTION_HAS_NO_INPUT                             37180L
#define PI_ERROR_SYS_CONNECTION_HAS_NO_INPUT__37180                      37180L
#define PI_ERROR_SYS_CONNECTION_HAS_NO_OUTPUT                            37181L
#define PI_ERROR_SYS_CONNECTION_HAS_NO_OUTPUT__37181                     37181L
#define PI_ERROR_SYS_CONNECTION_NOT_FOUND                                37183L
#define PI_ERROR_SYS_CONNECTION_NOT_FOUND__37183                         37183L
#define PI_ERROR_SYS_INPUT_PORT_NOT_CONNECTED                            37184L
#define PI_ERROR_SYS_INPUT_PORT_NOT_CONNECTED__37184                     37184L
#define PI_ERROR_SYS_DATA_CORRUPT                                        37446L
#define PI_ERROR_SYS_DATA_CORRUPT__37446                                 37446L
#define PI_ERROR_SYS_FW_UPDATE_ERROR                                     37682L
#define PI_ERROR_SYS_FW_UPDATE_ERROR__37682                              37682L
#define PI_ERROR_SYS_UNIT_NOT_FOUND                                      37692L
#define PI_ERROR_SYS_UNIT_NOT_FOUND__37692                               37692L
#define PI_ERROR_SYS_UNIT_TYPE_NOT_SUPPORTED                             37889L
#define PI_ERROR_SYS_UNIT_TYPE_NOT_SUPPORTED__37889                      37889L
#define PI_ERROR_SYS_NOT_ENOUGH_MEMORY                                   37918L
#define PI_ERROR_SYS_NOT_ENOUGH_MEMORY__37918                            37918L
#define PI_ERROR_SYS_NO_DATA_AVAILABLE                                   37919L
#define PI_ERROR_SYS_NO_DATA_AVAILABLE__37919                            37919L
#define PI_ERROR_SYS_FLASH_READ_FAILED                                   37938L
#define PI_ERROR_SYS_FLASH_READ_FAILED__37938                            37938L
#define PI_ERROR_SYS_FATAL_ERROR                                         37988L
#define PI_ERROR_SYS_FATAL_ERROR__37988                                  37988L

///////////////////////////////////////////////////////////////////////////////
//
//   obsolet, provided for backward compatibility
//
///////////////////////////////////////////////////////////////////////////////

#define PI_CNTR_MOVE_WITHOUT_INI  5  // name "INI" is misleading - we mean "reference
#define PI_CNTR_INVALID_AXIS      23 // misleading name: INVALID means something different than "illegal"

